# Generated by Django 3.2.9 on 2021-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20211202_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-12-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
